"""Initial schema

Revision ID: 318d0e4bd080
Revises: None
Create Date: 2026-09-11 17:29:36.834335+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '318d0e4bd080'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('github_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_user_id', name='uq_github_accounts_user_github_user')
    )
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=False)
    op.create_table('github_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_account_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['github_account_id'], ['github_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_index(op.f('ix_github_installations_github_account_id'), 'github_installations', ['github_account_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.UUID(), nullable=True),
    sa.Column('github_repo_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clone_url', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['github_installation_id'], ['github_installations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id')
    )
    op.create_index(op.f('ix_repositories_github_installation_id'), 'repositories', ['github_installation_id'], unique=False)
    op.create_table('repository_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('index_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("index_status IN ('PENDING', 'SUCCESS', 'FAILED')", name='ck_repository_versions_index_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'commit_sha', name='uq_repository_versions_repository_commit')
    )
    op.create_index('ix_repository_versions_repository_id', 'repository_versions', ['repository_id'], unique=False)
    op.create_table('user_repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', name='uq_user_repositories_user_repository')
    )
    op.create_index('ix_user_repositories_repository_id', 'user_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_user_repositories_user_id'), 'user_repositories', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_type IN ('TECH_STACK', 'ARCHITECTURE', 'STATISTICS', 'OVERVIEW')", name='ck_analysis_results_type'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_version_id', 'analysis_type', name='uq_analysis_results_version_type')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_repository_user_created_at', 'conversations', ['repository_id', 'user_id', 'created_at'], unique=False)
    op.create_index('ix_conversations_repository_version_id', 'conversations', ['repository_version_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_version_id', 'file_path', name='uq_files_version_path')
    )
    op.create_index('ix_files_file_path', 'files', ['file_path'], unique=False)
    op.create_index('ix_files_repository_version_id', 'files', ['repository_version_id'], unique=False)
    op.create_table('index_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'FETCHING', 'INDEXING', 'ANALYZING', 'READY', 'FAILED')", name='ck_index_jobs_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_index_jobs_repository_id_created_at', 'index_jobs', ['repository_id', 'created_at'], unique=False)
    op.create_index('ix_index_jobs_repository_version_id', 'index_jobs', ['repository_version_id'], unique=False)
    op.create_index('uq_index_jobs_one_active_per_repository', 'index_jobs', ['repository_id'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'FETCHING', 'INDEXING', 'ANALYZING')"))
    op.create_table('file_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('target_file_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("relationship_type IN ('IMPORTS', 'DEPENDS_ON')", name='ck_file_relationships_type'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_relationships_repository_version_id', 'file_relationships', ['repository_version_id'], unique=False)
    op.create_index('ix_file_relationships_source_file_id', 'file_relationships', ['source_file_id'], unique=False)
    op.create_index('ix_file_relationships_target_file_id', 'file_relationships', ['target_file_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=False),
    sa.Column('symbol_type', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbols_file_id_name', 'symbols', ['file_id', 'name'], unique=False)
    op.create_index('ix_symbols_qualified_name', 'symbols', ['qualified_name'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_chunks_file_id_chunk_index', 'code_chunks', ['file_id', 'chunk_index'], unique=False)
    op.create_index('ix_code_chunks_symbol_id', 'code_chunks', ['symbol_id'], unique=False)
    op.create_table('symbol_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('source_symbol_id', sa.UUID(), nullable=False),
    sa.Column('target_symbol_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("relationship_type IN ('CALLS', 'REFERENCES', 'INHERITS', 'IMPLEMENTS')", name='ck_symbol_relationships_type'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbol_relationships_repository_version_id', 'symbol_relationships', ['repository_version_id'], unique=False)
    op.create_index('ix_symbol_relationships_source_symbol_id', 'symbol_relationships', ['source_symbol_id'], unique=False)
    op.create_index('ix_symbol_relationships_target_symbol_id', 'symbol_relationships', ['target_symbol_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('code_chunk_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_chunk_id'], ['code_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_code_chunk_id', 'citations', ['code_chunk_id'], unique=False)
    op.create_index('ix_citations_message_id', 'citations', ['message_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_chunk_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['code_chunk_id'], ['code_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_chunk_id', 'model_name', name='uq_embeddings_chunk_model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.drop_index('ix_citations_message_id', table_name='citations')
    op.drop_index('ix_citations_code_chunk_id', table_name='citations')
    op.drop_table('citations')
    op.drop_index('ix_symbol_relationships_target_symbol_id', table_name='symbol_relationships')
    op.drop_index('ix_symbol_relationships_source_symbol_id', table_name='symbol_relationships')
    op.drop_index('ix_symbol_relationships_repository_version_id', table_name='symbol_relationships')
    op.drop_table('symbol_relationships')
    op.drop_index('ix_code_chunks_symbol_id', table_name='code_chunks')
    op.drop_index('ix_code_chunks_file_id_chunk_index', table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index('ix_symbols_qualified_name', table_name='symbols')
    op.drop_index('ix_symbols_file_id_name', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_file_relationships_target_file_id', table_name='file_relationships')
    op.drop_index('ix_file_relationships_source_file_id', table_name='file_relationships')
    op.drop_index('ix_file_relationships_repository_version_id', table_name='file_relationships')
    op.drop_table('file_relationships')
    op.drop_index('uq_index_jobs_one_active_per_repository', table_name='index_jobs', postgresql_where=sa.text("status IN ('QUEUED', 'FETCHING', 'INDEXING', 'ANALYZING')"))
    op.drop_index('ix_index_jobs_repository_version_id', table_name='index_jobs')
    op.drop_index('ix_index_jobs_repository_id_created_at', table_name='index_jobs')
    op.drop_table('index_jobs')
    op.drop_index('ix_files_repository_version_id', table_name='files')
    op.drop_index('ix_files_file_path', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_conversations_repository_version_id', table_name='conversations')
    op.drop_index('ix_conversations_repository_user_created_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_user_repositories_user_id'), table_name='user_repositories')
    op.drop_index('ix_user_repositories_repository_id', table_name='user_repositories')
    op.drop_table('user_repositories')
    op.drop_index('ix_repository_versions_repository_id', table_name='repository_versions')
    op.drop_table('repository_versions')
    op.drop_index(op.f('ix_repositories_github_installation_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_github_installations_github_account_id'), table_name='github_installations')
    op.drop_table('github_installations')
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.drop_table('github_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
