"""Add agent run and checkpoints

Revision ID: a5633f95e4b0
Revises: 'd8416eafd6e5'
Create Date: 2026-09-17 15:05:53.240266+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5633f95e4b0'
down_revision: Union[str, None] = 'd8416eafd6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_version_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_version_id'], ['repository_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_conversation_id', 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('ix_agent_runs_repository_version_id', 'agent_runs', ['repository_version_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_table('agent_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_checkpoints_agent_run_id_created_at', 'agent_checkpoints', ['agent_run_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_checkpoints_agent_run_id_created_at', table_name='agent_checkpoints')
    op.drop_table('agent_checkpoints')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_repository_version_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_conversation_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
