"""Add provider and dimension to embeddings

Revision ID: d8416eafd6e5
Revises: 'a52c9b3f4cf3'
Create Date: 2026-09-16 16:36:59.167609+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8416eafd6e5'
down_revision: Union[str, None] = 'a52c9b3f4cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('provider', sa.String(length=255), nullable=False, server_default='google'))
    op.add_column('embeddings', sa.Column('dimension', sa.Integer(), nullable=False, server_default='768'))
    # Remove server defaults after creation
    op.alter_column('embeddings', 'provider', server_default=None)
    op.alter_column('embeddings', 'dimension', server_default=None)
    
    import pgvector
    # Change vector column to exactly 768 dimensions
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               type_=pgvector.sqlalchemy.vector.VECTOR(768),
               postgresql_using='vector::vector(768)')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import pgvector
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(768),
               type_=pgvector.sqlalchemy.vector.VECTOR(),
               postgresql_using='vector::vector')
    op.drop_column('embeddings', 'dimension')
    op.drop_column('embeddings', 'provider')
    # ### end Alembic commands ###
